(library
 (name base_test)
 (libraries base core.base_for_tests base_test_helpers
   bignum.bigint expect_test_helpers_core.expect_test_helpers_base expectable
;   unboxed.float_u unboxed.int32_u unboxed.int64_u unboxed.nativeint_u
   portable.test_helpers sexp_grammar_validation sexplib stdio)
 (modules (:standard \ test_base_containers_mono test_base_containers_poly test_hash_set))
 (inline_tests (flags -drop-tag no-js -drop-tag 64-bits-only -drop-tag no-wasm) (modes js wasm))
 (preprocess
  (pps ppx_jane -dont-apply=pipebang -no-check-on-extensions)))
